export type Paper = {
  id: string;
  title: string;
  authors: string;
  year: string;
  priority: "필수" | "권장" | "해당자" | "방어" | "학술 JB";
  note: string;
};

export const PAPERS: Paper[] = [
  {
    id: "2406.11717",
    title: "Refusal in Language Models Is Mediated by a Single Direction",
    authors: "Arditi, Obeso, Syed, Paleka, Panickssery, Gurnee, Nanda",
    year: "NeurIPS 2024",
    priority: "필수",
    note: "거절 방향 가설의 원형. 13개 오픈 챗 모델(최대 72B). 지우면 거절이 줄고 더하면 무해한 질문도 거절.",
  },
  {
    id: "2512.13655",
    title: "Comparative Analysis of LLM Abliteration Methods",
    authors: "Young",
    year: "2026-01 v2",
    priority: "필수",
    note: "Heretic·DECCP·ErisForge·FailSpy를 16개 7B–14B Instruct에서 비교. 호환성 Heretic 16/16. GSM8K이 가장 민감. 벤치 Δ는 3모델 평균.",
  },
  {
    id: "2607.17427",
    title: "Abliteration Is Not a Scalpel",
    authors: "Fafuła",
    year: "2026-07",
    priority: "필수",
    note: "거절 없는 과제에서 낙관·헤징 이동. 알파 없음. 템플릿·양자화 오염이 결론을 뒤집음.",
  },
  {
    id: "2512.18901",
    title: "Gabliteration: Adaptive Multi-Directional Neural Weight Modification",
    authors: "Gülmez",
    year: "2025-12 / v3 2026-01",
    priority: "권장",
    note: "SVD 다방향 + 분리도 기반 층 선택 + ridge 투영. 소형(0.6B–4B) 검증.",
  },
  {
    id: "2607.02714",
    title: "Not All Refusals Are Equal: How Safety Alignment Fails Cybersecurity at Scale",
    authors: "Hadetskyi et al.",
    year: "2026-07",
    priority: "해당자",
    note: "도메인 대조 쌍으로 선택적 완화. 1T Kimi K2 사례. 교차 도메인 spillover가 남음.",
  },
  {
    id: "2602.02132",
    title: "There Is More to Refusal in LLMs than a Single Direction",
    authors: "Joad, Hawasly, Boughorbel, Durrani, Sencar",
    year: "2026-02",
    priority: "권장",
    note: "단일 방향 가설을 직접 반박. 여러 거절·비준수 방향. 그래도 공유 손잡이처럼 동작하는 축이 많음.",
  },
  {
    id: "2505.19056",
    title: "An Embarrassingly Simple Defense Against LLM Abliteration Attacks",
    authors: "Abu Shairah, Hammoud, Ghanem, Turkiyyah",
    year: "2025-05",
    priority: "방어",
    note: "extended-refusal 학습. Llama-2-7B-Chat·Qwen2.5에서 ablation 후 거부율 하락을 크게 줄였다는 보고.",
  },
  {
    id: "2608.18093",
    title: "Abliteration Mitigation via Refusal Aliases",
    authors: "Truong",
    year: "2026-08",
    priority: "방어",
    note: "거절 별칭을 복제해 단일 r 제거를 비싸게. 조사일 신규.",
  },
  {
    id: "2606.05396",
    title: "Willing but Unable",
    authors: "Carleo et al.",
    year: "2026-06",
    priority: "권장",
    note: "코드 LLM에서 ‘거절’과 ‘못 함’을 같은 실패로 묶지 말 것.",
  },
  {
    id: "2606.04160",
    title: "Expert-Aware Refusal Steering",
    authors: "Marbut, Olson, Wheeler",
    year: "2026-06",
    priority: "해당자",
    note: "MoE에서 전문가별 거절 방향과 라우팅. 전 expert 동일 r은 과잉 수정.",
  },
  {
    id: "2605.08513",
    title: "A Single Neuron Is Sufficient to Bypass Safety Alignment",
    authors: "Kazemi, Chegini, Safi",
    year: "2026-05",
    priority: "권장",
    note: "방향보다 더 국소: 단일 뉴런 억제로 정렬을 우회할 수 있다는 보고.",
  },
  {
    id: "2605.21706",
    title: "Latent-space Attacks for Refusal Evasion",
    authors: "Piras, Mura, Brau, Pintor, Oneto, Roli, Biggio",
    year: "2026-05",
    priority: "방어",
    note: "거절 프로브 경계 안쪽이 아니라 순응 영역으로 표현을 밀어 넣는 잠재 공간 회피.",
  },
  {
    id: "2505.17306",
    title: "Refusal Direction is Universal Across Safety-Aligned Languages",
    authors: "Wang, Wang, Liu, Schuetze, Plank",
    year: "2025-05",
    priority: "해당자",
    note: "14언어 PolyRefuse. 영어 r의 교차언어 전이. 한국어 홀드아웃의 근거.",
  },
  {
    id: "2310.08419",
    title: "Jailbreaking Black Box Large Language Models in Twenty Queries (PAIR)",
    authors: "Chao et al.",
    year: "2023-10",
    priority: "학술 JB",
    note: "공격자-판사 루프. 학술 알고리즘만. 유해 생성에 쓰지 말 것.",
  },
  {
    id: "2312.02119",
    title: "TAP: Tree of Attacks with Pruning",
    authors: "Mehrotra et al.",
    year: "NeurIPS 2024",
    priority: "학술 JB",
    note: "트리 탐색+가지치기. 방어 연구 이해용.",
  },
  {
    id: "2404.01833",
    title: "Great, Now Write an Article About That (Crescendo)",
    authors: "Russinovich, Salem, Eldan",
    year: "arXiv 2024 / v3 2025-02",
    priority: "학술 JB",
    note: "다턴 자기인용 에스컬레이션. 단턴 필터의 맹점.",
  },
  {
    id: "2602.15001",
    title: "Boundary Point Jailbreaking",
    authors: "UK AISI",
    year: "2026-02",
    priority: "학술 JB",
    note: "1비트 피드백으로 분류기 경계를 찾는 블랙박스 탐색.",
  },
  {
    id: "2603.22061",
    title: "On the Failure of Topic-Matched Contrast Baselines",
    authors: "Petrov",
    year: "2026-03",
    priority: "해당자",
    note: "주제만 맞춘 대조 쌍으로는 거절 방향이 안 나온다는 음결과.",
  },
  {
    id: "2606.23375",
    title: "Legal Over-alignment and Heretic LoRA",
    authors: "Wuhrmann et al.",
    year: "2026-06",
    priority: "해당자",
    note: "법률 과잉정렬에 Heretic을 LoRA로 적용한 사례. 배포 형태 참고.",
  },
  {
    id: "2603.10012",
    title: "Military-tuned model + Heretic (authorized study)",
    authors: "Fitzgerald et al.",
    year: "2026-03",
    priority: "해당자",
    note: "인가 연구 맥락의 거절률 변화 보고. 방법 복제 대상 아님.",
  },
  {
    id: "2605.26526",
    title: "Safeguarded open-weight models: abliteration + prefill range",
    authors: "Kuo et al.",
    year: "2026-05",
    priority: "방어",
    note: "가드레일 모델에서 ablation과 prefilling 결합 시 ASR 범위 보고. 방어 함의.",
  },
  {
    id: "2604.05267",
    title: "Do Domain-specific Experts exist in MoE-based LLMs? (DSMoE)",
    authors: "Do et al.",
    year: "ACL Findings 2026",
    priority: "권장",
    note: "10개 MoE에서 수학 expert 존재. 학습 없는 라우터 변조가 SFT를 이기기도. 물리·생물·화학 확장.",
  },
  {
    id: "2401.14196",
    title:
      "DeepSeek-Coder: When the Large Language Model Meets Programming -- The Rise of Code Intelligence",
    authors: "Guo et al.",
    year: "2024-01",
    priority: "해당자",
    note: "프로젝트 수준 코드 말뭉치 2T 토큰과 fill-in-the-blank 학습을 사용한 오픈 코드 모델 선례.",
  },
  {
    id: "2402.03300",
    title: "DeepSeekMath: Pushing the Limits of Mathematical Reasoning in Open Language Models",
    authors: "Shao et al.",
    year: "2024-02",
    priority: "해당자",
    note: "수학 CPT+SFT와 GRPO의 공개 선례. 분야 변형의 수학 카드 근거.",
  },
  {
    id: "2406.04313",
    title: "Improving Alignment and Robustness with Circuit Breakers",
    authors: "Zou et al.",
    year: "2024-06",
    priority: "방어",
    note: "유해 표현 궤적을 끊음. ablation의 거울. 멀티모달 적용 보고.",
  },
  {
    id: "2310.01405",
    title: "Representation Engineering: A Top-Down Approach to AI Transparency",
    authors: "Zou, Phan, et al.",
    year: "2023-10",
    priority: "권장",
    note: "RepE. steering·circuit breaker의 공통 조상.",
  },
  {
    id: "2306.01708",
    title: "TIES-Merging: Resolving Interference When Merging Models",
    authors: "Yadav et al.",
    year: "NeurIPS 2023",
    priority: "해당자",
    note: "LoRA/모델 병합 시 부호 충돌. 도메인 adapter+ablation 합성.",
  },
  {
    id: "2606.26161",
    title: "Refusal Lives Downstream of Persona in Chat Models",
    authors: "Zhong, Li",
    year: "ICML 2026 workshop",
    priority: "권장",
    note: "순응 페르소나가 거절을 게이트. Llama 거절 97%→2%. 후반 층.",
  },
  {
    id: "2502.17420",
    title: "The Geometry of Refusal: Concept Cones and Representational Independence",
    authors: "Wollschläger et al.",
    year: "2025-02",
    priority: "권장",
    note: "거절이 다차원 cone. 단일 방향 한계의 기하.",
  },
  {
    id: "2606.22686",
    title: "The Geometry of Refusal: Linear Instability (Contrastive Logit Steering)",
    authors: "Ratnakar, Vats",
    year: "2026-06",
    priority: "해당자",
    note: "시스템 프롬프트 대조로 r. 최적화 없는 조향.",
  },
  {
    id: "2604.04385",
    title: "How Alignment Routes: Policy Circuits in Language Models",
    authors: "Frank",
    year: "2026-04",
    priority: "해당자",
    note: "희소 게이트-증폭 회로로 정책 강도 연속 제어.",
  },
  {
    id: "2603.11388",
    title: "Deactivating Refusal Triggers",
    authors: "Xue, Qi, Liu, Chen, Pedarsani",
    year: "2026-03",
    priority: "해당자",
    note: "정렬이 만든 과잉거절 트리거 큐.",
  },
  {
    id: "2410.03415",
    title: "Mitigating False Refusal via Single Vector Ablation",
    authors: "Cao et al.",
    year: "ICLR 2025",
    priority: "권장",
    note: "거짓 거절만 직교화. 전 범주 uncensored의 대안.",
  },
  {
    id: "2509.09708",
    title: "Dissecting Large-Language-Model Refusal",
    authors: "Prakash et al.",
    year: "AAAI 2026",
    priority: "해당자",
    note: "SAE로 거절을 뒤집는 특징 집합. 연구용.",
  },
  {
    id: "2409.05907",
    title: "Programming Refusal with Conditional Activation Steering (CAST)",
    authors: "Lee, Padhi, Ramamurthy, et al.",
    year: "ICLR 2025 Spotlight",
    priority: "권장",
    note: "가중치 불변 스티어링. IBM activation-steering.",
  },
  {
    id: "2603.13359",
    title: "Discovering and Steering Category-Specific Refusal Directions",
    authors: "Alagharu, Singh, Shamsudeen, Wu, Panda",
    year: "2026-03",
    priority: "권장",
    note: "거절 토큰 SFT가 범주별 축을 남김. 전역 r의 보완.",
  },
  {
    id: "2512.16602",
    title: "Refusal Steering: Fine-grained Control over Refusal Behaviour",
    authors: "García-Ferrero, Montero, Orus",
    year: "2025-12",
    priority: "해당자",
    note: "민감 주제 거절 세기의 연속 조절.",
  },
  {
    id: "2601.08489",
    title: "Surgical Refusal Ablation",
    authors: "Cristofano",
    year: "2026-01",
    priority: "권장",
    note: "능력 방향과 분리된 거절 벡터.",
  },
];

export const REPOS = [
  {
    name: "p-e-w/heretic",
    url: "https://github.com/p-e-w/heretic",
    role: "기본 도구",
    license: "AGPL-3.0",
    use: "TPE 최적화 직교화. pip install git+https://github.com/p-e-w/heretic.git@3521f8648a0dccf6e12a92666862632235fac7e6",
  },
  {
    name: "elder-plinius/OBLITERATUS",
    url: "https://github.com/elder-plinius/OBLITERATUS",
    role: "헤드리스 ablation CLI",
    license: "AGPL-3.0",
    use: "pip install git+https://github.com/elder-plinius/OBLITERATUS.git@205d28a11352313eb68954223948c9ce9b10cb39 · obliteratus obliterate --method advanced. argparse에 failspy 없음.",
  },
  {
    name: "andyrdt/refusal_direction",
    url: "https://github.com/andyrdt/refusal_direction",
    role: "논문 공식 코드",
    license: "Apache-2.0",
    use: "Arditi 재현. r을 직접 그릴 때",
  },
  {
    name: "ant-research/Awesome-Refusal-Suppression",
    url: "https://github.com/ant-research/Awesome-Refusal-Suppression",
    role: "인덱스",
    license: "큐레이션",
    use: "논문·리포 목록의 출발점",
  },
  {
    name: "FailSpy/abliterator",
    url: "https://github.com/FailSpy/abliterator",
    role: "원조 실용",
    license: "MIT",
    use: "초기 표준. 호환은 좁음. console script 없음. analog apply_ablation.py.",
  },
  {
    name: "Goekdeniz-Guelmez/gabliteration",
    url: "https://github.com/Goekdeniz-Guelmez/gabliteration",
    role: "연구 코드",
    license: "MIT",
    use: "다방향·ridge 재현. gabliterate @1498fc74. stdin 1은 analog.",
  },
  {
    name: "heterodoxin/apostate",
    url: "https://github.com/heterodoxin/apostate",
    role: "MIT KCRN/diode CLI",
    license: "MIT",
    use: "console script apostate. apostate ablate --model --out @be36269d (2026-09-07). PyPI 404. 선택 칩.",
  },
  {
    name: "wuwangzhang1216/abliterix",
    url: "https://github.com/wuwangzhang1216/abliterix",
    role: "2026 Heretic 파생",
    license: "AGPL-3.0",
    use: "선택 칩. pip git @5d58cea9 (2026-09-01). --model.model-id --non-interactive --non-interactive-output-dir. vendor 금지.",
  },
  {
    name: "AIAnytime/ablate",
    url: "https://github.com/AIAnytime/ablate",
    role: "MIT 무인 CLI",
    license: "MIT",
    use: "선택 칩. console script ablate. git @6b89bea10dd2305b374004147ccc2b3a16769c38 = ablate-llm 0.2.0. ablate run --model --output --save-model. bake는 output/model.",
  },
  {
    name: "jwest33/abliterator",
    url: "https://github.com/jwest33/abliterator",
    role: "MIT 직교 투영 CLI",
    license: "MIT",
    use: "선택 칩. console script abliterate. FailSpy 아님. git @6ca3356e. --batch --model_path --output_path (underscore). PyPI abliterator 404. pip abliteration 금지.",
  },
  {
    name: "nanofatdog/LLM-abliterate",
    url: "https://github.com/nanofatdog/LLM-abliterate",
    role: "Apache 무인 extract/apply CLI",
    license: "Apache-2.0",
    use: "선택 칩. console script llm-abliterate @f01cec96. alias abliterate 금지(jwest). extract --out; apply --direction --lam 1.65 --save. LICENSE 파일 404, pyproject Apache-2.0.",
  },
  {
    name: "josepha-mayo/model-unfetter",
    url: "https://github.com/josepha-mayo/model-unfetter",
    role: "Apache 무인 ablate CLI",
    license: "Apache-2.0",
    use: "선택 칩. console script unfetter @4c9548c2. unfetter ablate MODEL --output --backend gpu. --strength 파서 기본 1.0. setup.py entry_points.",
  },
  {
    name: "NousResearch/llm-abliteration",
    url: "https://github.com/NousResearch/llm-abliteration",
    role: "Transformers",
    license: "GPL-3.0",
    use: "빠른 교육용 파이프라인. vendor 금지.",
  },
  {
    name: "AUGMXNT/deccp",
    url: "https://github.com/AUGMXNT/deccp",
    role: "단일 패스",
    license: "Apache-2.0",
    use: "능력 보존 비교 실험. 01/03 파일명 @1a6d5571. deccp 명령 없음.",
  },
  {
    name: "mlabonne/abliteration (HF blog)",
    url: "https://huggingface.co/blog/mlabonne/abliteration",
    role: "입문 글",
    license: "블로그",
    use: "초보 진입. 2024-06 해설",
  },
  {
    name: "TransformerLens",
    url: "https://github.com/TransformerLensOrg/TransformerLens",
    role: "해석",
    license: "MIT",
    use: "훅·캐시·패치. FailSpy 노트북 의존. 포트 안 함.",
  },
  {
    name: "Tsadoq/ErisForge",
    url: "https://github.com/Tsadoq/ErisForge",
    role: "레이어 래퍼",
    license: "MIT",
    use: "레이어 래퍼 라이브러리. console script 없음. analog apply_ablation.py.",
  },
  {
    name: "Orion-zhen/abliteration",
    url: "https://github.com/Orion-zhen/abliteration",
    role: "YAML 단일패스",
    license: "GPL-3.0",
    use: "python abliterate.py config.yaml. vendor 금지.",
  },
  {
    name: "elder-plinius/OBLITERATUS (pinned fork)",
    url: "https://github.com/elder-plinius/OBLITERATUS",
    role: "GUI·다중전략 (pinned)",
    license: "AGPL-3.0-or-later",
    use: "팩 git @fb38a3b0. HEAD 2026-08-30 ls-remote cd8b0b78 드리프트, 재핀 안 함. vendor 금지.",
  },
  {
    name: "mainlp/False-Refusal-Mitigation",
    url: "https://github.com/mainlp/False-Refusal-Mitigation",
    role: "과잉거절만",
    license: "ICLR 2025 코드",
    use: "거짓 거절 벡터. 전 범주 아님",
  },
  {
    name: "ricyoung/abliteration-comparison",
    url: "https://github.com/ricyoung/abliteration-comparison",
    role: "벤치",
    license: "논문 재현",
    use: "4도구 호환·GSM8K 표",
  },
  {
    name: "GraySwanAI/circuit-breakers",
    url: "https://github.com/GraySwanAI/circuit-breakers",
    role: "방어",
    license: "논문",
    use: "ablation의 거울. 유해 궤적 차단",
  },
  {
    name: "wollschlager/geometry-of-refusal",
    url: "https://github.com/wollschlager/geometry-of-refusal",
    role: "원뿔",
    license: "논문 코드",
    use: "다차원 거절 기하 재현",
  },
  {
    name: "knoveleng/orthex",
    url: "https://github.com/knoveleng/orthex",
    role: "MIT --config CLI",
    license: "MIT",
    use: "console script orthex 있음. --config required. configs/data 휠 밖, architecture_adapter 필수. 칩 아님.",
  },
  {
    name: "FiditeNemini/mlx-abliteration",
    url: "https://github.com/FiditeNemini/mlx-abliteration",
    role: "Apple MLX 스크립트",
    license: "Apache-2.0",
    use: "python cli.py argparse. console script 없음. MLX-only. CUDA 팩 칩 아님.",
  },
  {
    name: "knol3j/cli-abliterated",
    url: "https://github.com/knol3j/cli-abliterated",
    role: "GGUF 채팅",
    license: "MIT",
    use: "cli-abliterated 콘솔 스크립트는 채팅. ablation 아님.",
  },
  {
    name: "0x0806/UnleashedLLM",
    url: "https://github.com/0x0806/UnleashedLLM",
    role: "다운로더/채팅",
    license: "LICENSE 404",
    use: "Unleashed 라벨. ablation CLI 없음. analog 칩 발명 금지.",
  },
  {
    name: "adybag14-cyber/Abliteration",
    url: "https://github.com/adybag14-cyber/Abliteration",
    role: "핸드북",
    license: "Apache-2.0",
    use: "문서+abliterate-cxx 릴리스. pip console script 없음. 칩 아님.",
  },
] as const;

export const METHODS = [
  {
    key: "A",
    title: "방향 추출",
    body: "평균 차 · SVD · SAE 특징. 무엇을 지울지.",
  },
  {
    key: "B",
    title: "적용 연산",
    body: "직교화 · ridge · 노름 보존 · steering. 어떻게 지울지.",
  },
  {
    key: "C",
    title: "탐색",
    body: "수동 · 그리드 · TPE · 분리도 기반 층 선택.",
  },
  {
    key: "D",
    title: "범위",
    body: "전 범주 · 도메인 특화 · 문체/slop · 단일 개념.",
  },
  {
    key: "E",
    title: "복구",
    body: "없음 · DPO/ORPO · orthogonal LoRA.",
  },
  {
    key: "F",
    title: "방어",
    body: "extended-refusal · alias · 앱 필터 · 가중치 서명.",
  },
] as const;

export const CHAPTERS = [
  { range: "1–5", title: "도입 · 용어 · Arditi · 후속 논문 · 도구" },
  { range: "6–10", title: "Heretic kernel · steering · 도메인 · healing · 모델 표" },
  { range: "11–17", title: "학술 jailbreak · LoRA · 비교 · 평가 · 워크플로 · 방어" },
  { range: "18–31", title: "Q&A · 로드맵 · 윤리 · 실패 · 생태계 · 한국어" },
  { range: "32–55", title: "기하 · 연대기 · CLI · MoE · 비전 · 실험 해석" },
  { range: "56–80", title: "수치 예제 · 런북 · 카드 · 하드웨어 · 에필로그" },
  { range: "81–90", title: "운영 · 신화 · 수식 치트 · 90일 계획 · 콜로폰" },
  { range: "91–100", title: "택소노미 · 논문 · 리포 · 선택 트리 · 북마크" },
  { range: "101–108", title: "확장 서지 · 클릭 링크 · 논문별 한 장 노트" },
  { range: "109–127", title: "분야 특화 · 수학·물리·공학·화학·생물 · 사이버 · 레드/블루 · MoE" },
  { range: "128–142", title: "기존 로컬 모델 변형 · 분야별 양자화 · imatrix · 재측정" },
  { range: "143–163", title: "보강: 회로차단기 · 한국어 모델 · 서빙 · 병합 · RAG · 가드" },
  { range: "164–173", title: "2026-08-24: 페르소나 · CLS · 원뿔 · 거짓거절 · OBLITERATUS" },
  { range: "174–184", title: "Heretic 외 도구 상세 사용법 · DECCP · ErisForge · FailSpy" },
  { range: "185–195", title: "도구 실측: Young 표 · GSM8K · KL · 평가 프로토콜" },
  { range: "196–198", title: "CAST · 범주별 거절 · 세기 조절" },
  { range: "부록", title: "대화 흐름 · 문헌 · 수식 · 대조표 · VRAM · 명령 요약" },
] as const;

export const DOMAINS = [
  {
    name: "수학",
    quant: "Q6_K / Q8_0",
    transform: "정답 필터 SFT + 코드 도구. CPT보다 채점된 풀이.",
    gate: "GSM8K · 자릿수 오류",
  },
  {
    name: "물리",
    quant: "Q5–Q6",
    transform: "형식 SFT + arXiv RAG + 단위 검사기.",
    gate: "단위 틀린 답",
  },
  {
    name: "공학",
    quant: "Q5_K_M",
    transform: "코드 강모델 + 데이터시트 RAG. 숫자 출처 강제.",
    gate: "스펙 숫자 일치",
  },
  {
    name: "화학",
    quant: "Q5–Q6 (SMILES는 Q6)",
    transform: "문헌 RAG ± 그래프 모델. 합성 경로 창작 제한.",
    gate: "SMILES 파서 유효성",
  },
  {
    name: "생물·생명공",
    quant: "Q5_K_M",
    transform: "PubMed RAG + 문헌 SFT. 서열은 ESM. 고위험 거절 유지.",
    gate: "고위험 거절 · 심볼 정규화",
  },
  {
    name: "사이버 방어",
    quant: "Q4–Q5",
    transform: "CVE RAG + 완화 SFT. 전 범주 ablation 금지에 가깝다.",
    gate: "CVE ID 정확 · 비인가 거절",
  },
  {
    name: "레드팀",
    quant: "평가 하네스 (학습 아님)",
    transform: "발견→완화 쌍만. 시뮬은 시뮬 안에서.",
    gate: "스코프 문서",
  },
  {
    name: "블루팀",
    quant: "Q4_K_M",
    transform: "티켓 문체 SFT + 플레이북 RAG. 도구는 HITL.",
    gate: "오격리 제안율",
  },
  {
    name: "MoE",
    quant: "라우터 상위 비트 · 중요 expert 보호",
    transform: "히스토그램 → DSMoE → expert LoRA. 라우터 동결.",
    gate: "도메인 vs 일반 히스토그램",
  },
] as const;

export const TOOL_BENCH = [
  { tool: "Heretic", cov: "16/16", gsm: "−7.81 pp*", mmlu: "−0.78", time: "33–109분" },
  { tool: "DECCP", cov: "11/16", gsm: "−0.13 pp", mmlu: "−0.61", time: "~2분" },
  { tool: "ErisForge", cov: "9/16", gsm: "−0.28 pp", mmlu: "−0.12", time: "래퍼" },
  { tool: "FailSpy", cov: "5/16", gsm: "—", mmlu: "—", time: "캐시" },
] as const;

export const HERETIC_EIGHT = [
  { m: "Zephyr-7B-beta", r: "2/100", kl: "0.076", t: "40m" },
  { m: "DeepSeek-7B-chat", r: "16/100", kl: "0.043", t: "59m" },
  { m: "Mistral-7B-v0.3", r: "16/100", kl: "0.317", t: "39m" },
  { m: "Llama-3.1-8B", r: "24/100", kl: "0.056", t: "33m" },
  { m: "Qwen3-8B", r: "25/100", kl: "0.210", t: "56m" },
  { m: "Yi-1.5-9B", r: "25/100", kl: "0.248", t: "57m" },
  { m: "Qwen2.5-7B", r: "42/100", kl: "1.646", t: "41m" },
  { m: "StableLM-2-12B", r: "54/100", kl: "1.605", t: "109m" },
] as const;

export function paperAbs(id: string) {
  return `https://arxiv.org/abs/${id}`;
}
export function paperPdf(id: string) {
  return `https://arxiv.org/pdf/${id}`;
}
export function paperHtml(id: string) {
  return `https://arxiv.org/html/${id}`;
}
export function paperHf(id: string) {
  return `https://huggingface.co/papers/${id}`;
}
