/**
 * Canonical compute provider catalog for Abliterater.
 * Cross-platform: URL paths use forward slashes only; no OS filesystem paths here.
 *
 * Status honesty:
 * - active: live HTTP/local adapter usable today
 * - catalog: registered for UI/selection; no live adapter yet
 * - degraded: known flaky / limited
 * - planned: future consideration
 */

export type ComputeKind = "iaas" | "rental" | "saas" | "aggregator" | "local" | "onprem";
export type ComputeStatus = "active" | "catalog" | "degraded" | "planned";
export type ComputeFit = "train" | "abliterate" | "infer";

export type ComputeProvider = {
  id: string;
  label: string;
  labelKo?: string;
  labelEn?: string;
  kind: ComputeKind;
  regions: string[];
  gpuSkus: string[];
  authType: string;
  pricingModels: string[];
  fits: ComputeFit[];
  supportsSsh: boolean;
  supportsCustomDocker: boolean;
  launchTemplate?: string;
  status: ComputeStatus;
  docsUrl?: string;
  launchHints?: string;
  /** Alias note (e.g. vast ↔ vastai). */
  aliasOf?: string;
};

const ALL_FITS: ComputeFit[] = ["train", "abliterate", "infer"];
const TRAIN_ABL: ComputeFit[] = ["train", "abliterate"];
const INFER: ComputeFit[] = ["infer"];

function p(partial: ComputeProvider): ComputeProvider {
  return partial;
}

/** Full registry — ids are kebab-case and stable. */
export const COMPUTE_PROVIDERS: readonly ComputeProvider[] = [
  // --- Live adapters (HTTP) ---
  p({
    id: "runpod",
    label: "RunPod",
    labelKo: "RunPod",
    labelEn: "RunPod",
    kind: "rental",
    regions: ["US", "EU", "ASIA"],
    gpuSkus: ["RTX4090", "A100", "H100", "H200"],
    authType: "api-key",
    pricingModels: ["on-demand", "spot"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    launchTemplate: "runpodctl / REST pods",
    status: "active",
    docsUrl: "https://docs.runpod.io/",
    launchHints: "Live adapter: list/read pods via RunPod REST.",
  }),
  p({
    id: "vast",
    label: "Vast.ai",
    labelKo: "Vast.ai",
    labelEn: "Vast.ai",
    kind: "rental",
    regions: ["global"],
    gpuSkus: ["RTX4090", "A6000", "A100", "H100"],
    authType: "api-key",
    pricingModels: ["auction", "on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    launchTemplate: "vastai CLI / REST instances",
    status: "active",
    docsUrl: "https://docs.vast.ai/",
    launchHints: "Alias: vastai. Live adapter: GET console.vast.ai/api/v0 instances (list/read).",
    aliasOf: "vastai",
  }),
  p({
    id: "lambda",
    label: "Lambda Cloud",
    labelKo: "Lambda",
    labelEn: "Lambda Cloud",
    kind: "rental",
    regions: ["US"],
    gpuSkus: ["A10", "A100", "H100"],
    authType: "api-key",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    launchTemplate: "Lambda Cloud API launch",
    status: "active",
    docsUrl: "https://docs.lambdalabs.com/",
    launchHints: "Live adapter: list/read instances via Lambda Cloud API.",
  }),

  // --- Modal (job-oriented; catalog UI + optional non-HTTP stub) ---
  p({
    id: "modal",
    label: "Modal",
    labelKo: "Modal",
    labelEn: "Modal",
    kind: "saas",
    regions: ["US"],
    gpuSkus: ["T4", "A10", "A100", "H100"],
    authType: "token",
    pricingModels: ["per-second"],
    fits: ALL_FITS,
    supportsSsh: false,
    supportsCustomDocker: true,
    launchTemplate: "modal run",
    status: "catalog",
    docsUrl: "https://modal.com/docs",
    launchHints:
      "Python SDK / modal CLI primary. No fake REST list — register for catalog + pack launch hints.",
  }),

  // --- Local / SSH (active local adapters) ---
  p({
    id: "localhost-ollama",
    label: "Ollama (localhost)",
    labelKo: "Ollama 로컬",
    labelEn: "Ollama (localhost)",
    kind: "local",
    regions: ["local"],
    gpuSkus: ["host-gpu"],
    authType: "manual",
    pricingModels: ["free"],
    fits: INFER,
    supportsSsh: false,
    supportsCustomDocker: false,
    status: "active",
    docsUrl: "https://ollama.com/",
    launchHints: "Local OpenAI-compatible HTTP on localhost — no cloud job API.",
  }),
  p({
    id: "localhost-lmstudio",
    label: "LM Studio (localhost)",
    labelKo: "LM Studio 로컬",
    labelEn: "LM Studio (localhost)",
    kind: "local",
    regions: ["local"],
    gpuSkus: ["host-gpu"],
    authType: "manual",
    pricingModels: ["free"],
    fits: INFER,
    supportsSsh: false,
    supportsCustomDocker: false,
    status: "active",
    docsUrl: "https://lmstudio.ai/",
    launchHints: "Local server — no cloud job API.",
  }),
  p({
    id: "local-cuda",
    label: "Local CUDA",
    labelKo: "로컬 CUDA",
    labelEn: "Local CUDA",
    kind: "local",
    regions: ["local"],
    gpuSkus: ["NVIDIA"],
    authType: "manual",
    pricingModels: ["free"],
    fits: ALL_FITS,
    supportsSsh: false,
    supportsCustomDocker: true,
    status: "active",
    launchHints: "Host NVIDIA GPU via run.sh / run.ps1.",
  }),
  p({
    id: "local-rocm",
    label: "Local ROCm",
    labelKo: "로컬 ROCm",
    labelEn: "Local ROCm",
    kind: "local",
    regions: ["local"],
    gpuSkus: ["AMD"],
    authType: "manual",
    pricingModels: ["free"],
    fits: ALL_FITS,
    supportsSsh: false,
    supportsCustomDocker: true,
    status: "active",
    launchHints: "Host AMD GPU.",
  }),
  p({
    id: "local-metal",
    label: "Local Metal",
    labelKo: "로컬 Metal",
    labelEn: "Local Metal",
    kind: "local",
    regions: ["local"],
    gpuSkus: ["Apple"],
    authType: "manual",
    pricingModels: ["free"],
    fits: ALL_FITS,
    supportsSsh: false,
    supportsCustomDocker: false,
    status: "active",
    launchHints: "macOS unified memory / MPS.",
  }),
  p({
    id: "local-cpu",
    label: "Local CPU",
    labelKo: "로컬 CPU",
    labelEn: "Local CPU",
    kind: "local",
    regions: ["local"],
    gpuSkus: ["CPU"],
    authType: "manual",
    pricingModels: ["free"],
    fits: ["infer", "abliterate"],
    supportsSsh: false,
    supportsCustomDocker: true,
    status: "active",
    launchHints: "Host CPU / llama.cpp / OpenBLAS — keep existing Studio COMPUTES entry.",
  }),
  p({
    id: "ssh",
    label: "SSH remote",
    labelKo: "SSH 원격",
    labelEn: "SSH remote",
    kind: "onprem",
    regions: ["user"],
    gpuSkus: ["remote"],
    authType: "manual",
    pricingModels: ["free"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "active",
    launchHints:
      "Validation-only target registry; execution owned by ssh-execution (not this catalog).",
  }),

  // --- Hyperscalers (catalog; azure-ml equal among peers) ---
  p({
    id: "aws-ec2",
    label: "AWS EC2",
    kind: "iaas",
    regions: ["us-east-1", "us-west-2", "eu-west-1", "ap-northeast-2"],
    gpuSkus: ["g5", "p4", "p5"],
    authType: "aws-creds",
    pricingModels: ["on-demand", "spot"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://docs.aws.amazon.com/ec2/",
    launchHints: "Pack emits aws ec2 run-instances skeleton.",
  }),
  p({
    id: "gcp-gce",
    label: "GCP GCE",
    kind: "iaas",
    regions: ["us-central1", "europe-west4", "asia-northeast3"],
    gpuSkus: ["A2", "A3", "G2"],
    authType: "gcloud",
    pricingModels: ["on-demand", "spot"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://cloud.google.com/compute/docs/gpus",
    launchHints: "Pack emits gcloud compute instances create skeleton.",
  }),
  p({
    id: "azure-ml",
    label: "Azure ML",
    labelKo: "Azure ML",
    labelEn: "Azure Machine Learning",
    kind: "iaas",
    regions: ["eastus", "westeurope", "koreacentral"],
    gpuSkus: ["NC", "ND"],
    authType: "azure-cli",
    pricingModels: ["on-demand", "spot"],
    fits: TRAIN_ABL,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://learn.microsoft.com/azure/machine-learning/",
    launchHints: "One hyperscaler among many — not a default-only preset.",
  }),
  p({
    id: "oracle-oci",
    label: "Oracle OCI",
    kind: "iaas",
    regions: ["us-ashburn-1", "eu-frankfurt-1"],
    gpuSkus: ["A10", "A100", "H100"],
    authType: "oci-api-key",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://docs.oracle.com/en-us/iaas/Content/Compute/References/computeshapes.htm",
    launchHints: "GPU shapes via OCI Compute.",
  }),
  p({
    id: "azure-vm",
    label: "Azure VM",
    labelKo: "Azure VM",
    labelEn: "Azure VM",
    kind: "iaas",
    regions: ["eastus", "westeurope", "koreacentral"],
    gpuSkus: ["NC", "ND"],
    authType: "azure-cli",
    pricingModels: ["on-demand", "spot"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://learn.microsoft.com/azure/virtual-machines/",
    launchHints: "Hyperscaler VM peer of azure-ml — not a privileged default.",
  }),
  p({
    id: "aws-sagemaker",
    label: "AWS SageMaker",
    kind: "saas",
    regions: ["us-east-1", "us-west-2"],
    gpuSkus: ["ml.p4", "ml.p5", "ml.g5"],
    authType: "aws-creds",
    pricingModels: ["per-job"],
    fits: TRAIN_ABL,
    supportsSsh: false,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://docs.aws.amazon.com/sagemaker/",
    launchHints: "Existing Studio COMPUTES entry — training jobs, not a default.",
  }),
  p({
    id: "gcp-vertex",
    label: "GCP Vertex AI",
    kind: "saas",
    regions: ["us-central1", "europe-west4"],
    gpuSkus: ["a2", "a3"],
    authType: "gcloud",
    pricingModels: ["per-job"],
    fits: TRAIN_ABL,
    supportsSsh: false,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://cloud.google.com/vertex-ai/docs",
    launchHints: "Existing Studio COMPUTES entry — custom jobs.",
  }),

  // --- KR / APAC ---
  p({
    id: "naver-cloud",
    label: "Naver Cloud",
    labelKo: "네이버 클라우드",
    kind: "iaas",
    regions: ["KR"],
    gpuSkus: ["GPU-Server"],
    authType: "ncloud-api-key",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://guide.ncloud-docs.com/",
    launchHints: "KR residency GPU Server.",
  }),
  p({
    id: "kt-cloud",
    label: "KT Cloud",
    labelKo: "KT 클라우드",
    kind: "iaas",
    regions: ["KR"],
    gpuSkus: ["GPU"],
    authType: "kt-api-key",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    launchHints: "KR residency.",
  }),
  p({
    id: "samsung-sds",
    label: "Samsung SDS",
    labelKo: "삼성SDS",
    kind: "iaas",
    regions: ["KR"],
    gpuSkus: ["GPU"],
    authType: "enterprise",
    pricingModels: ["contract"],
    fits: TRAIN_ABL,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "planned",
    launchHints: "Enterprise KR — planned.",
  }),
  p({
    id: "kakao-cloud",
    label: "Kakao Cloud",
    labelKo: "카카오클라우드",
    kind: "iaas",
    regions: ["KR"],
    gpuSkus: ["GPU"],
    authType: "kakao-api-key",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    launchHints: "KR cloud GPU.",
  }),
  p({
    id: "alibaba-egs",
    label: "Alibaba EGS",
    kind: "iaas",
    regions: ["cn", "ap"],
    gpuSkus: ["A10", "A100", "H20"],
    authType: "aliyun-ak",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    launchHints: "Elastic GPU Service.",
  }),
  p({
    id: "tencent-gpu",
    label: "Tencent GPU",
    kind: "iaas",
    regions: ["cn", "ap"],
    gpuSkus: ["GN", "GT"],
    authType: "tencent-ak",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
  }),

  // --- GPU rental / marketplaces (existing seed) ---
  p({
    id: "thunder-compute",
    label: "Thunder Compute",
    kind: "rental",
    regions: ["US"],
    gpuSkus: ["A100", "H100"],
    authType: "api-key",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://www.thundercompute.com/docs/api-reference/instances/create-instance",
    launchHints: "Tier A future live: REST instance CRUD (Bearer).",
  }),
  p({
    id: "massed-compute",
    label: "Massed Compute",
    kind: "rental",
    regions: ["US"],
    gpuSkus: ["A6000", "A100", "H100"],
    authType: "api-key",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://vm-docs.massedcompute.com/api/v1",
    launchHints: "Tier A future live: OpenAPI VM lifecycle (Bearer).",
  }),
  p({
    id: "shadeform",
    label: "Shadeform",
    kind: "aggregator",
    regions: ["multi"],
    gpuSkus: ["multi-cloud"],
    authType: "api-key",
    pricingModels: ["pass-through"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://docs.shadeform.ai/api-reference/authentication",
    launchHints: "Tier A future live: X-API-KEY multi-cloud instance API.",
  }),
  p({
    id: "nebius",
    label: "Nebius",
    kind: "iaas",
    regions: ["EU"],
    gpuSkus: ["H100", "H200"],
    authType: "api-key",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://docs.nebius.com/",
    launchHints: "EU GPU cloud.",
  }),
  p({
    id: "coreweave",
    label: "CoreWeave",
    kind: "iaas",
    regions: ["US", "EU"],
    gpuSkus: ["A100", "H100", "H200"],
    authType: "api-key",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
  }),
  p({
    id: "crusoe",
    label: "Crusoe",
    kind: "iaas",
    regions: ["US"],
    gpuSkus: ["A100", "H100"],
    authType: "api-key",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
  }),
  p({
    id: "voltage-park",
    label: "Voltage Park",
    kind: "rental",
    regions: ["US"],
    gpuSkus: ["H100"],
    authType: "api-key",
    pricingModels: ["on-demand", "reserved"],
    fits: TRAIN_ABL,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://cloud-api.voltagepark.com/api/v1/openapi.json",
    launchHints: "OpenAPI Bearer — bare-metal H100 clusters.",
  }),
  p({
    id: "paperspace",
    label: "Paperspace",
    kind: "rental",
    regions: ["US", "EU"],
    gpuSkus: ["A4000", "A6000", "H100"],
    authType: "api-key",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
  }),
  p({
    id: "saladcloud",
    label: "SaladCloud",
    kind: "rental",
    regions: ["global"],
    gpuSkus: ["consumer-gpu"],
    authType: "api-key",
    pricingModels: ["on-demand"],
    fits: ["infer", "abliterate"],
    supportsSsh: false,
    supportsCustomDocker: true,
    status: "catalog",
  }),
  p({
    id: "tensordock",
    label: "TensorDock",
    kind: "rental",
    regions: ["global"],
    gpuSkus: ["RTX4090", "A6000"],
    authType: "api-key",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "degraded",
    launchHints: "Degraded — do not prefer as default live adapter.",
  }),

  // --- SaaS / inference / jobs ---
  p({
    id: "hf-jobs",
    label: "Hugging Face Jobs",
    kind: "saas",
    regions: ["HF"],
    gpuSkus: ["a10g", "a100", "h100"],
    authType: "hf-token",
    pricingModels: ["per-job"],
    fits: TRAIN_ABL,
    supportsSsh: false,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://huggingface.co/docs/huggingface_hub/guides/jobs",
    launchHints: "hf jobs run skeleton in pack.",
  }),
  p({
    id: "together",
    label: "Together Inference",
    kind: "saas",
    regions: ["US"],
    gpuSkus: ["hosted"],
    authType: "api-key",
    pricingModels: ["token"],
    fits: INFER,
    supportsSsh: false,
    supportsCustomDocker: false,
    status: "catalog",
    docsUrl: "https://docs.together.ai/",
    launchHints: "Inference API; see together-compute for rentable clusters.",
  }),
  p({
    id: "together-compute",
    label: "Together GPU Clusters",
    kind: "rental",
    regions: ["US"],
    gpuSkus: ["H100", "H200", "B200"],
    authType: "api-key",
    pricingModels: ["cluster"],
    fits: TRAIN_ABL,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://docs.together.ai/docs/gpu-clusters-overview",
    launchHints: "Tier A future live: rentable K8s/Slurm clusters.",
  }),
  p({
    id: "fireworks",
    label: "Fireworks",
    kind: "saas",
    regions: ["US"],
    gpuSkus: ["hosted"],
    authType: "api-key",
    pricingModels: ["token"],
    fits: INFER,
    supportsSsh: false,
    supportsCustomDocker: false,
    status: "catalog",
  }),
  p({
    id: "fireworks-training",
    label: "Fireworks Training",
    kind: "saas",
    regions: ["US"],
    gpuSkus: ["dedicated"],
    authType: "api-key",
    pricingModels: ["gpu-hour"],
    fits: TRAIN_ABL,
    supportsSsh: false,
    supportsCustomDocker: false,
    status: "catalog",
    docsUrl: "https://docs.fireworks.ai/fine-tuning/training-api/introduction",
    launchHints: "Managed training jobs (not raw VM rental).",
  }),
  p({
    id: "baseten",
    label: "Baseten",
    kind: "saas",
    regions: ["US"],
    gpuSkus: ["hosted"],
    authType: "api-key",
    pricingModels: ["token"],
    fits: INFER,
    supportsSsh: false,
    supportsCustomDocker: true,
    status: "catalog",
  }),
  p({
    id: "replicate",
    label: "Replicate",
    kind: "saas",
    regions: ["US"],
    gpuSkus: ["hosted"],
    authType: "api-key",
    pricingModels: ["per-second"],
    fits: INFER,
    supportsSsh: false,
    supportsCustomDocker: true,
    status: "catalog",
  }),
  p({
    id: "nvidia-nim",
    label: "NVIDIA NIM",
    kind: "saas",
    regions: ["NVIDIA"],
    gpuSkus: ["NIM"],
    authType: "ngc-api-key",
    pricingModels: ["hosted"],
    fits: INFER,
    supportsSsh: false,
    supportsCustomDocker: true,
    status: "catalog",
  }),
  p({
    id: "dgx-cloud",
    label: "DGX Cloud",
    kind: "iaas",
    regions: ["NVIDIA"],
    gpuSkus: ["H100", "H200"],
    authType: "enterprise",
    pricingModels: ["contract"],
    fits: TRAIN_ABL,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "planned",
  }),
  p({
    id: "colab",
    label: "Google Colab",
    kind: "saas",
    regions: ["GCP"],
    gpuSkus: ["T4", "A100", "L4"],
    authType: "google",
    pricingModels: ["notebook"],
    fits: ALL_FITS,
    supportsSsh: false,
    supportsCustomDocker: false,
    status: "catalog",
    docsUrl: "https://colab.research.google.com/",
    launchHints: "Existing Studio COMPUTES notebook target.",
  }),
  p({
    id: "lightning",
    label: "Lightning Studios",
    kind: "rental",
    regions: ["US"],
    gpuSkus: ["T4", "L4", "A100"],
    authType: "api-key",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://lightning.ai/docs",
    launchHints: "Existing Studio COMPUTES Lightning Studios entry.",
  }),

  // --- Research 2026-09-11 new catalog entries ---
  p({
    id: "jarvislabs",
    label: "Jarvislabs",
    kind: "rental",
    regions: ["IN", "global"],
    gpuSkus: ["RTX6000", "A100", "H100"],
    authType: "api-key",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://docs.jarvislabs.ai/sdk/",
    launchHints: "Tier A future live: JL_API_KEY / SDK instance lifecycle.",
  }),
  p({
    id: "oblivus",
    label: "Oblivus Cloud",
    kind: "rental",
    regions: ["global"],
    gpuSkus: ["A100", "H100"],
    authType: "api-key",
    pricingModels: ["per-minute"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://docs.oblivus.com/api/credentials/",
    launchHints: "API key + token credentials; short jobs.",
  }),
  p({
    id: "prime-intellect",
    label: "Prime Intellect",
    kind: "rental",
    regions: ["global"],
    gpuSkus: ["H100", "H200"],
    authType: "api-key",
    pricingModels: ["on-demand"],
    fits: TRAIN_ABL,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://docs.primeintellect.ai/api-reference/api-keys",
    launchHints: "Tier A future live: pods API (Bearer).",
  }),
  p({
    id: "cherry-servers",
    label: "Cherry Servers",
    kind: "iaas",
    regions: ["EU"],
    gpuSkus: ["dedicated-gpu"],
    authType: "api-key",
    pricingModels: ["monthly", "hourly"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://www.cherryservers.com/developer-automation",
    launchHints: "EU bare-metal GPU via Cherry API/SDKs.",
  }),
  p({
    id: "latitude-sh",
    label: "Latitude.sh",
    kind: "iaas",
    regions: ["global"],
    gpuSkus: ["bare-metal-gpu"],
    authType: "api-key",
    pricingModels: ["hourly"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://www.latitude.sh/docs/api-reference/summary",
    launchHints: "JSON:API bare-metal/VM with GPU filters.",
  }),
  p({
    id: "hostkey",
    label: "HOSTKEY",
    kind: "iaas",
    regions: ["EU", "US"],
    gpuSkus: ["A5000", "dedicated"],
    authType: "api-key",
    pricingModels: ["monthly"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://hostkey.com/documentation/apidocs/api_index/",
    launchHints: "InvAPI + Terraform GPU presets.",
  }),
  p({
    id: "seeweb",
    label: "Seeweb",
    kind: "iaas",
    regions: ["EU"],
    gpuSkus: ["ECS-GPU"],
    authType: "api-token",
    pricingModels: ["hourly"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://docs.seeweb.it/en/hosting/cloudserver/cs-gpu/introduction/",
    launchHints: "X-APITOKEN ECS GPU Cloud Servers.",
  }),
  p({
    id: "contabo-gpu",
    label: "Contabo GPU",
    kind: "rental",
    regions: ["EU"],
    gpuSkus: ["GPU-VPS"],
    authType: "oauth",
    pricingModels: ["monthly"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "planned",
    docsUrl: "https://api.contabo.com/",
    launchHints: "Uncertain GPU product_id availability — verify before live adapter.",
  }),
  p({
    id: "gcore-gpu",
    label: "Gcore GPU",
    kind: "iaas",
    regions: ["EU", "US", "APAC"],
    gpuSkus: ["virtual-gpu-cluster"],
    authType: "api-key",
    pricingModels: ["on-demand"],
    fits: TRAIN_ABL,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://docs.gcore.com/edge-ai/ai-infrastructure/create-a-virtual-gpu-cluster",
    launchHints: "Virtual GPU cluster create/list/action.",
  }),
  p({
    id: "deep-infra-gpu",
    label: "DeepInfra GPU Instances",
    kind: "rental",
    regions: ["US"],
    gpuSkus: ["B200", "H100"],
    authType: "api-key",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://docs.deepinfra.com/gpu-instances/overview",
    launchHints: "Tier A future live: DEEPINFRA_TOKEN SSH containers.",
  }),
  p({
    id: "hyperbolic",
    label: "Hyperbolic",
    kind: "rental",
    regions: ["global"],
    gpuSkus: ["marketplace"],
    authType: "api-key",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://www.hyperbolic.ai/docs/on-demand/quickstart",
    launchHints: "Marketplace rent/create/terminate via REST.",
  }),
  p({
    id: "spheron",
    label: "Spheron",
    kind: "aggregator",
    regions: ["decentralized"],
    gpuSkus: ["marketplace"],
    authType: "api-key",
    pricingModels: ["lease"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://docs.spheron.ai/api-reference",
    launchHints: "Decentralized GPU offers + deployments.",
  }),
  p({
    id: "digitalocean-gpu",
    label: "DigitalOcean GPU Droplets",
    kind: "iaas",
    regions: ["nyc", "tor", "atl"],
    gpuSkus: ["gpu-droplet"],
    authType: "api-key",
    pricingModels: ["hourly"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://docs.digitalocean.com/products/droplets/how-to/gpu/create/",
    launchHints: "Tier A future live: DO token + GPU size slugs.",
  }),
  p({
    id: "exoscale-gpu",
    label: "Exoscale GPU",
    kind: "iaas",
    regions: ["EU"],
    gpuSkus: ["gpu*"],
    authType: "api-key",
    pricingModels: ["hourly"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://community.exoscale.com/reference/api/compute/instance/",
    launchHints: "EU GPU instance types via APIv2.",
  }),
  p({
    id: "hot-aisle",
    label: "Hot Aisle",
    kind: "rental",
    regions: ["US"],
    gpuSkus: ["MI300X", "MI355X"],
    authType: "api-key",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://hotaisle.xyz/docs/api",
    launchHints: "AMD Instinct VMs — diversifies beyond NVIDIA.",
  }),
  p({
    id: "sf-compute",
    label: "SF Compute",
    kind: "rental",
    regions: ["US"],
    gpuSkus: ["H100"],
    authType: "api-key",
    pricingModels: ["orderbook"],
    fits: TRAIN_ABL,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://docs.sfcompute.com/preview/using-the-api",
    launchHints: "Orderbook-style time-window H100 capacity.",
  }),
  p({
    id: "novita",
    label: "Novita AI",
    kind: "rental",
    regions: ["global"],
    gpuSkus: ["GPU-instance"],
    authType: "api-key",
    pricingModels: ["on-demand"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://novita.ai/docs/api-reference/gpus-v2-create-instance",
    launchHints: "GPU instance lifecycle v2 API.",
  }),
  p({
    id: "clore-ai",
    label: "Clore.ai",
    kind: "aggregator",
    regions: ["decentralized"],
    gpuSkus: ["marketplace"],
    authType: "api-key",
    pricingModels: ["order"],
    fits: ALL_FITS,
    supportsSsh: true,
    supportsCustomDocker: true,
    status: "catalog",
    docsUrl: "https://docs.clore.ai/dev/reference/api-reference",
    launchHints: "Decentralized marketplace create_order API.",
  }),
] as const;

export const computeProviderIds: readonly string[] = COMPUTE_PROVIDERS.map((x) => x.id);

export function computeProviderById(id: string): ComputeProvider | undefined {
  return COMPUTE_PROVIDERS.find((x) => x.id === id || x.aliasOf === id);
}

export function computeProvidersByKind(kind: ComputeKind): ComputeProvider[] {
  return COMPUTE_PROVIDERS.filter((x) => x.kind === kind);
}

export function computeProvidersByStatus(status: ComputeStatus): ComputeProvider[] {
  return COMPUTE_PROVIDERS.filter((x) => x.status === status);
}

/** Aliases requested by catalog API: byId / byKind / ids(). */
export function byId(id: string): ComputeProvider | undefined {
  return computeProviderById(id);
}

export function byKind(kind: ComputeKind): ComputeProvider[] {
  return computeProvidersByKind(kind);
}

export function ids(): readonly string[] {
  return computeProviderIds;
}
