export type SupportTier =
  | "catalog"
  | "discovery-live"
  | "auth-contract"
  | "auth-live"
  | "lifecycle-contract"
  | "lifecycle-live"
  | "workload-live";
export type AuthKind =
  "api-key" | "oauth2" | "cloud-cli" | "signed-request" | "kubeconfig" | "manual";
export type ProviderCapability = {
  id: string;
  name: string;
  auth: AuthKind[];
  tier: SupportTier;
  instance: boolean;
  job: boolean;
  list: boolean;
  read: boolean;
  create: boolean;
  stop: boolean;
  remove: boolean;
  logs: boolean;
  artifacts: boolean;
  webhook: boolean;
  officialDocs: string;
  verifiedAt: string;
  limitations: string[];
  regions?: string[];
  hardware?: string[];
  spot?: boolean;
  idleShutdown?: boolean;
};

export const PROVIDER_CAPABILITIES: ProviderCapability[] = [
  {
    id: "runpod",
    name: "RunPod",
    auth: ["api-key"],
    tier: "auth-contract",
    instance: true,
    job: true,
    list: true,
    read: true,
    create: true,
    stop: true,
    remove: true,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.runpod.io/api-reference/overview",
    verifiedAt: "2026-09-14",
    limitations: [
      "User-key create after budget ack. Not lifecycle-live.",
      "Web needs provider CORS; desktop uses IPC.",
      "Pod status is not training success.",
    ],
  },
  {
    id: "lambda",
    name: "Lambda Cloud",
    auth: ["api-key"],
    tier: "auth-contract",
    instance: true,
    job: false,
    list: true,
    read: true,
    create: true,
    stop: true,
    remove: true,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs-api.lambda.ai/api/cloud",
    verifiedAt: "2026-09-14",
    limitations: [
      "User-key create after budget ack. Not lifecycle-live.",
      "Launch requires region_name, instance_type_name, ssh_key_names.",
    ],
  },
  {
    id: "vast",
    name: "Vast.ai",
    auth: ["api-key"],
    tier: "auth-contract",
    instance: true,
    job: false,
    list: true,
    read: true,
    create: true,
    stop: false,
    remove: true,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.vast.ai/api-reference/introduction",
    verifiedAt: "2026-09-14",
    limitations: [
      "User-key create after budget ack. Not lifecycle-live.",
      "Create is PUT /asks/{offerId}/. stop ≠ destroy.",
    ],
  },
  {
    id: "modal",
    name: "Modal",
    auth: ["cloud-cli"],
    tier: "catalog",
    instance: false,
    job: true,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://modal.com/docs/guide",
    verifiedAt: "2026-09-12",
    limitations: ["Function/App/call 중심; VM CRUD로 취급하지 않음", "HTTP list 미구현"],
  },
  {
    id: "localhost_ollama",
    name: "Ollama (loopback)",
    auth: ["manual"],
    tier: "auth-contract",
    instance: false,
    job: false,
    list: true,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://github.com/ollama/ollama/blob/main/docs/api.md",
    verifiedAt: "2026-09-12",
    limitations: ["127.0.0.1:11434 GET /api/tags", "생성 성공이 아님"],
  },
  {
    id: "ssh",
    name: "SSH",
    auth: ["manual"],
    tier: "catalog",
    instance: true,
    job: true,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://www.openssh.com/manual.html",
    verifiedAt: "2026-09-12",
    limitations: ["plan-only; executable:false", "키는 팩에 넣지 않음"],
  },
  {
    id: "tensordock",
    name: "TensorDock",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://tensordock.com/",
    verifiedAt: "2026-09-12",
    limitations: ["degraded — Voltage Park 인수"],
  },
  {
    id: "azure",
    name: "Azure",
    auth: ["oauth2", "cloud-cli"],
    tier: "catalog",
    instance: true,
    job: true,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines",
    verifiedAt: "2026-09-09",
    limitations: ["CLI 로그인과 제품 adapter 통합은 별개", "GPU quota 별도"],
  },
  {
    id: "aws",
    name: "AWS",
    auth: ["cloud-cli", "signed-request"],
    tier: "catalog",
    instance: true,
    job: true,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.aws.amazon.com/AWSEC2/latest/APIReference/Welcome.html",
    verifiedAt: "2026-09-09",
    limitations: ["IAM SigV4/STS; EC2 API는 OAuth 아님"],
  },
  {
    id: "gcp",
    name: "Google Cloud",
    auth: ["oauth2", "cloud-cli"],
    tier: "catalog",
    instance: true,
    job: true,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://cloud.google.com/compute/docs/reference/rest/v1/instances",
    verifiedAt: "2026-09-09",
    limitations: ["ADC/OAuth; API 연결 미구현"],
  },

  {
    id: "localhost-ollama",
    name: "Ollama (localhost)",
    auth: ["manual"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://ollama.com/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "localhost-lmstudio",
    name: "LM Studio (localhost)",
    auth: ["manual"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://lmstudio.ai/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "local-cuda",
    name: "Local CUDA",
    auth: ["manual"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.nvidia.com/cuda/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "local-rocm",
    name: "Local ROCm",
    auth: ["manual"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://rocm.docs.amd.com/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "local-metal",
    name: "Local Metal",
    auth: ["manual"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://developer.apple.com/metal/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "local-cpu",
    name: "Local CPU",
    auth: ["manual"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://github.com/ggml-org/llama.cpp",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "aws-ec2",
    name: "AWS EC2",
    auth: ["cloud-cli", "signed-request"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.aws.amazon.com/ec2/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "gcp-gce",
    name: "GCP GCE",
    auth: ["oauth2", "cloud-cli"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://cloud.google.com/compute/docs/gpus",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "azure-ml",
    name: "Azure ML",
    auth: ["oauth2", "cloud-cli"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://learn.microsoft.com/azure/machine-learning/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "oracle-oci",
    name: "Oracle OCI",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.oracle.com/en-us/iaas/Content/Compute/References/computeshapes.htm",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "azure-vm",
    name: "Azure VM",
    auth: ["oauth2", "cloud-cli"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://learn.microsoft.com/azure/virtual-machines/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "aws-sagemaker",
    name: "AWS SageMaker",
    auth: ["cloud-cli", "signed-request"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.aws.amazon.com/sagemaker/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "gcp-vertex",
    name: "GCP Vertex AI",
    auth: ["oauth2", "cloud-cli"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://cloud.google.com/vertex-ai/docs",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "naver-cloud",
    name: "Naver Cloud",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://guide.ncloud-docs.com/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "kt-cloud",
    name: "KT Cloud",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://cloud.kt.com/docs/open-api-guide/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "samsung-sds",
    name: "Samsung SDS",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://cloud.samsungsds.com/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "kakao-cloud",
    name: "Kakao Cloud",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.kakaocloud.com/en/service/bcs/gpu",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "alibaba-egs",
    name: "Alibaba EGS",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://www.alibabacloud.com/help/en/egs",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "tencent-gpu",
    name: "Tencent GPU",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://www.tencentcloud.com/document/product/560",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "thunder-compute",
    name: "Thunder Compute",
    auth: ["api-key"],
    tier: "auth-contract",
    instance: true,
    job: false,
    list: true,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://www.thundercompute.com/docs/api-reference/instances/list-instances",
    verifiedAt: "2026-09-14",
    limitations: [
      "Contract tests only.",
      "GET /instances/list keyed map; per-id read is not in the public GET contract.",
      "Create in the Thunder Compute console.",
    ],
  },
  {
    id: "massed-compute",
    name: "Massed Compute",
    auth: ["api-key"],
    tier: "auth-contract",
    instance: true,
    job: false,
    list: true,
    read: true,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://vm-docs.massedcompute.com/api/v1",
    verifiedAt: "2026-09-14",
    limitations: [
      "계약 테스트만 통과; 실제 token 미검증",
      "GET /instance runningInstances; create/terminate 미배선",
    ],
  },
  {
    id: "shadeform",
    name: "Shadeform",
    auth: ["api-key"],
    tier: "auth-contract",
    instance: true,
    job: false,
    list: true,
    read: true,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.shadeform.ai/api-reference/instances/instances",
    verifiedAt: "2026-09-14",
    limitations: ["계약 테스트만 통과; 실제 token 미검증", "X-API-KEY list/read only"],
  },
  {
    id: "nebius",
    name: "Nebius",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.nebius.com/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "coreweave",
    name: "CoreWeave",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.coreweave.com/platform/instances/gpu-instances",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "crusoe",
    name: "Crusoe",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.crusoecloud.com/reference",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "voltage-park",
    name: "Voltage Park",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://cloud-api.voltagepark.com/api/v1/openapi.json",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "paperspace",
    name: "Paperspace",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.digitalocean.com/reference/paperspace/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "saladcloud",
    name: "SaladCloud",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.salad.com/reference",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "hf-jobs",
    name: "Hugging Face Jobs",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://huggingface.co/docs/huggingface_hub/guides/jobs",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "together",
    name: "Together Inference",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.together.ai/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "together-compute",
    name: "Together GPU Clusters",
    auth: ["api-key"],
    tier: "auth-contract",
    instance: true,
    job: false,
    list: true,
    read: true,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.together.ai/reference/clusters-list",
    verifiedAt: "2026-09-14",
    limitations: ["계약 테스트만 통과; 실제 token 미검증", "GET /compute/clusters; create 미배선"],
  },
  {
    id: "fireworks",
    name: "Fireworks",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.fireworks.ai/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "fireworks-training",
    name: "Fireworks Training",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.fireworks.ai/fine-tuning/training-api/introduction",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "baseten",
    name: "Baseten",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.baseten.co/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "replicate",
    name: "Replicate",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://replicate.com/docs",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "nvidia-nim",
    name: "NVIDIA NIM",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.nvidia.com/nim/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "dgx-cloud",
    name: "DGX Cloud",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.nvidia.com/dgx-cloud/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "colab",
    name: "Google Colab",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://colab.research.google.com/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "lightning",
    name: "Lightning Studios",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://lightning.ai/docs",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "jarvislabs",
    name: "Jarvislabs",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.jarvislabs.ai/sdk/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "oblivus",
    name: "Oblivus Cloud",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.oblivus.com/api/credentials/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "prime-intellect",
    name: "Prime Intellect",
    auth: ["api-key"],
    tier: "auth-contract",
    instance: true,
    job: false,
    list: true,
    read: true,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.primeintellect.ai/api-reference/pods/get-pods",
    verifiedAt: "2026-09-14",
    limitations: ["계약 테스트만 통과; 실제 token 미검증", "GET /pods/; create 미배선"],
  },
  {
    id: "cherry-servers",
    name: "Cherry Servers",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://www.cherryservers.com/developer-automation",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "latitude-sh",
    name: "Latitude.sh",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://www.latitude.sh/docs/api-reference/summary",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "hostkey",
    name: "HOSTKEY",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://hostkey.com/documentation/apidocs/api_index/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "seeweb",
    name: "Seeweb",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.seeweb.it/en/hosting/cloudserver/cs-gpu/introduction/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "contabo-gpu",
    name: "Contabo GPU",
    auth: ["oauth2"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://api.contabo.com/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "gcore-gpu",
    name: "Gcore GPU",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.gcore.com/edge-ai/ai-infrastructure/create-a-virtual-gpu-cluster",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "deep-infra-gpu",
    name: "DeepInfra GPU Instances",
    auth: ["api-key"],
    tier: "auth-contract",
    instance: true,
    job: false,
    list: true,
    read: true,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.deepinfra.com/gpu-instances/overview",
    verifiedAt: "2026-09-14",
    limitations: ["계약 테스트만 통과; 실제 token 미검증", "GET /v1/containers; create 미배선"],
  },
  {
    id: "hyperbolic",
    name: "Hyperbolic",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://www.hyperbolic.ai/docs/on-demand/quickstart",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "spheron",
    name: "Spheron",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.spheron.ai/api-reference",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "digitalocean-gpu",
    name: "DigitalOcean GPU Droplets",
    auth: ["api-key"],
    tier: "auth-contract",
    instance: true,
    job: false,
    list: true,
    read: true,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.digitalocean.com/reference/api/reference/droplets/",
    verifiedAt: "2026-09-14",
    limitations: [
      "계약 테스트만 통과; 실제 token 미검증",
      "GET /v2/droplets는 GPU만이 아님",
      "create 미배선",
    ],
  },
  {
    id: "exoscale-gpu",
    name: "Exoscale GPU",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://community.exoscale.com/reference/api/compute/instance/",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "hot-aisle",
    name: "Hot Aisle",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://hotaisle.xyz/docs/api",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "sf-compute",
    name: "SF Compute",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.sfcompute.com/preview/using-the-api",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "novita",
    name: "Novita AI",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://novita.ai/docs/api-reference/gpus-v2-create-instance",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
  {
    id: "clore-ai",
    name: "Clore.ai",
    auth: ["api-key"],
    tier: "catalog",
    instance: true,
    job: false,
    list: false,
    read: false,
    create: false,
    stop: false,
    remove: false,
    logs: false,
    artifacts: false,
    webhook: false,
    officialDocs: "https://docs.clore.ai/dev/reference/api-reference",
    verifiedAt: "2026-09-12",
    limitations: ["catalog entry from compute-providers; adapter not claimed"],
  },
];

export function capabilityOf(id: string): ProviderCapability | undefined {
  const direct = PROVIDER_CAPABILITIES.find((row) => row.id === id);
  if (direct) return direct;
  const aliased = id.includes("_") ? id.replaceAll("_", "-") : id.replaceAll("-", "_");
  return PROVIDER_CAPABILITIES.find((row) => row.id === aliased);
}

export type ComputeRuntimeKind = "local" | "create" | "pack-only";

/** Pack/audit kind. create=true is capability, not a live submit. */
export function computeRuntimeKind(id: string): ComputeRuntimeKind {
  if (id.startsWith("local-") || id.startsWith("localhost-") || id.startsWith("localhost_")) {
    return "local";
  }
  return capabilityOf(id)?.create === true ? "create" : "pack-only";
}

export type BudgetGuard = {
  maxUsd: number;
  maxMinutes: number;
  estimatedUsdPerHour: number;
  acknowledged: boolean;
};
export const BUDGET_ERROR = {
  ack: "BUDGET_ACK",
  usd: "BUDGET_USD",
  minutes: "BUDGET_MINUTES",
  rate: "BUDGET_RATE",
  over: "BUDGET_OVER",
} as const;

export function validateBudget(b: BudgetGuard): string[] {
  const errors: string[] = [];
  if (!b.acknowledged) errors.push(BUDGET_ERROR.ack);
  if (!Number.isFinite(b.maxUsd) || b.maxUsd <= 0) errors.push(BUDGET_ERROR.usd);
  if (!Number.isFinite(b.maxMinutes) || b.maxMinutes <= 0 || b.maxMinutes > 1440)
    errors.push(BUDGET_ERROR.minutes);
  if (!Number.isFinite(b.estimatedUsdPerHour) || b.estimatedUsdPerHour <= 0)
    errors.push(BUDGET_ERROR.rate);
  if ((b.estimatedUsdPerHour * b.maxMinutes) / 60 > b.maxUsd) errors.push(BUDGET_ERROR.over);
  return errors;
}
